### ISSUE TITLE
Can't compile on Plasma 6.7

### ISSUE THREAD

**Issue by na0miluv** [deanwyns/kwin-rounded-screen-corners#1]
I'm using Arch Linux, and already have all the packages necessary for compiling in here (kwin, extra-cmake-modules, vulkan-headers).

However, when I attempt to, I get the following error:

```
[  0%] Built target kwin_effect_roundedscreencorners_autogen_timestamp_deps
[ 20%] Automatic MOC for target kwin_effect_roundedscreencorners
AutoMoc warning
---------------
"SRC:/src/plugin.cpp"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, Q_GADGET_EXPORT, Q_ENUM_NS, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[ 20%] Built target kwin_effect_roundedscreencorners_autogen
[ 40%] Building CXX object src/CMakeFiles/kwin_effect_roundedscreencorners.dir/kwin_effect_roundedscreencorners_autogen/mocs_compilation.cpp.o
[ 60%] Building CXX object src/CMakeFiles/kwin_effect_roundedscreencorners.dir/plugin.cpp.o
[ 80%] Building CXX object src/CMakeFiles/kwin_effect_roundedscreencorners.dir/ScreenCornersEffect.cpp.o
/home/naomi/kwin-rounded-screen-corners/src/ScreenCornersEffect.cpp: In member function ‘virtual bool ScreenCornersEffect::isActive() const’:
/home/naomi/kwin-rounded-screen-corners/src/ScreenCornersEffect.cpp:49:34: error: ‘class KWin::GLShader’ has no member named ‘isValid’
   49 |     return m_shader && m_shader->isValid();
      |                                  ^~~~~~~
/home/naomi/kwin-rounded-screen-corners/src/ScreenCornersEffect.cpp: In member function ‘virtual void ScreenCornersEffect::paintScreen(const KWin::RenderTarget&, const KWin::RenderViewport&, int, const KWin::Region&, KWin::LogicalOutput*)’:
/home/naomi/kwin-rounded-screen-corners/src/ScreenCornersEffect.cpp:71:33: error: ‘class KWin::GLShader’ has no member named ‘isValid’
   71 |     if (!m_shader || !m_shader->isValid()) {
      |                                 ^~~~~~~
make[2]: *** [src/CMakeFiles/kwin_effect_roundedscreencorners.dir/build.make:107: src/CMakeFiles/kwin_effect_roundedscreencorners.dir/ScreenCornersEffect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:175: src/CMakeFiles/kwin_effect_roundedscreencorners.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
-- Install configuration: "Debug"
CMake Error at build/src/cmake_install.cmake:52 (file):
  file INSTALL cannot find
  "/home/naomi/kwin-rounded-screen-corners/build/lib/kwin/effects/plugins/kwin_effect_roundedscreencorners.so":
  No such file or directory.
Call Stack (most recent call first):
  build/cmake_install.cmake:47 (include)
```
Probably Kwin deprecated some GL stuff? I'm not really sure to be honest.
